<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use App\Models\Employee;
use App\Models\Organization;

class SDMEmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds for GAPURA ANGKASA SDM System
     * Data source: Dashboard Data SDM DATABASE SDM.csv
     * COMPLETE dengan 20 data karyawan yang 100% akurat dari CSV
     */
    public function run(): void
    {
        $this->command->info('Starting SDM Employee Seeding...');
        $this->command->info('Data Source: Dashboard Data SDM DATABASE SDM.csv');
        $this->command->info('Total employees to seed: 20');
        
        // Clear existing data
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('employees')->truncate();
        DB::table('organizations')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Seed Organizations based on CSV data
        $this->seedOrganizations();
        
        // Seed Employees from CSV data (COMPLETE 20 karyawan)
        $this->seedEmployees();

        $this->command->info('SDM Employee Seeding completed successfully!');
        $this->command->info('Total employees created: 20');
        $this->command->info('All data is 100% accurate from CSV file');
    }

    private function seedEmployees()
    {
        $this->command->info('Seeding employees from CSV data...');

        // COMPLETE 20 data karyawan dari CSV Dashboard Data SDM DATABASE SDM.csv
        // Semua field sudah disesuaikan dengan database schema
        $employees = [
            // Employee 1
            [
                'no' => 1,
                'nip' => '2160791',
                'nik' => null,
                'nama_lengkap' => 'I KETUT ADIYANA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'BO',
                'unit_organisasi' => 'Back Office',
                'nama_organisasi' => 'GENERAL AFFAIR & ADMINISTRATION',
                'nama_jabatan' => 'CONTROLLER HR & GA',
                'jabatan' => 'CONTROLLER HR & GA',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('01/05/2023'),
                'tmt_mulai_jabatan' => $this->parseDate('2023-02-15'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'P',
                'jenis_sepatu' => 'Pantofel',
                'ukuran_sepatu' => '37',
                'tempat_lahir' => 'MALANG',
                'tanggal_lahir' => $this->parseDate('1971-04-08'),
                'usia' => 54,
                'kota_domisili' => 'DENPASAR',
                'alamat' => 'Jalan Batas Dukuh Sari Gang Merpati No. B4, Pedungan, Denpasar, Bali',
                'pendidikan' => 'SEKOLAH MENENGAH ATAS',
                'pendidikan_terakhir' => 'SMA',
                'instansi_pendidikan' => 'SMAN 4 DENPASAR',
                'jurusan' => 'IPA',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 1990,
                'handphone' => '+6281353277157',
                'no_telepon' => '+6281353277157',
                'email' => 'ketut.adiyana@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-05-2027'),
                'grade' => 'IX',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'ACCOUNTING OFFICER',
                'weight' => 51,
                'height' => 154,
                'organization_id' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // Employee 2
            [
                'no' => 2,
                'nip' => '2170876',
                'nik' => null,
                'nama_lengkap' => 'A.A NGURAH GEDE AGUNG DHARMA PUTRA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'AS',
                'unit_organisasi' => 'Airside',
                'nama_organisasi' => 'OPERATION SERVICES',
                'nama_jabatan' => 'CONTROLLER OPERATION',
                'jabatan' => 'CONTROLLER OPERATION',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('02/04/2023'),
                'tmt_mulai_jabatan' => $this->parseDate('2023-04-02'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '42',
                'tempat_lahir' => 'DENPASAR',
                'tanggal_lahir' => $this->parseDate('1974-12-10'),
                'usia' => 50,
                'kota_domisili' => 'DENPASAR',
                'alamat' => 'Jalan Raya Pemogan Gang Anggrek VII/26, Pemogan, Denpasar, Bali',
                'pendidikan' => 'SEKOLAH MENENGAH ATAS',
                'pendidikan_terakhir' => 'SMA',
                'instansi_pendidikan' => 'SMA ANUGRAH',
                'jurusan' => 'IPA',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 1993,
                'handphone' => '+6285738605472',
                'no_telepon' => '+6285738605472',
                'email' => 'dharma.putra@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-01-2031'),
                'grade' => 'IX',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'SUPERVISOR',
                'kelas_jabatan' => 'CONTROLLER OPERATION',
                'weight' => 74,
                'height' => 170,
                'organization_id' => 2,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 3
            [
                'no' => 3,
                'nip' => '2150432',
                'nik' => null,
                'nama_lengkap' => 'I MADE SURYA DINATA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'GSE',
                'unit_organisasi' => 'GSE',
                'nama_organisasi' => 'GROUND SUPPORT EQUIPMENT',
                'nama_jabatan' => 'GSE OPERATOR',
                'jabatan' => 'GSE OPERATOR',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('15/03/2022'),
                'tmt_mulai_jabatan' => $this->parseDate('2022-03-15'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '41',
                'tempat_lahir' => 'SOLO',
                'tanggal_lahir' => $this->parseDate('1977-05-21'),
                'usia' => 48,
                'kota_domisili' => 'DENPASAR',
                'alamat' => 'Jl Imam Bonjol Gg.KertaPura IIIA/24, Denpasar Barat, Bali',
                'pendidikan' => 'DIPLOMA I',
                'pendidikan_terakhir' => 'D1',
                'instansi_pendidikan' => 'PRATAMA MULYA SURAKARTA',
                'jurusan' => 'KOMPUTER',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 1996,
                'handphone' => '+6285935077467',
                'no_telepon' => '+6285935077467',
                'email' => 'surya.dinata@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-06-2033'),
                'grade' => 'IX',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'GSE OPERATOR',
                'weight' => 90,
                'height' => 175,
                'organization_id' => 3,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 4
            [
                'no' => 4,
                'nip' => '2980836',
                'nik' => null,
                'nama_lengkap' => 'ASEP SETIAWAN',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'AS',
                'unit_organisasi' => 'Airside',
                'nama_organisasi' => 'OPERATION SERVICES',
                'nama_jabatan' => 'LOST & FOUND',
                'jabatan' => 'LOST & FOUND',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('01/11/2024'),
                'tmt_mulai_jabatan' => $this->parseDate('2024-11-01'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '43',
                'tempat_lahir' => 'BANDUNG',
                'tanggal_lahir' => $this->parseDate('1985-08-12'),
                'usia' => 40,
                'kota_domisili' => 'DENPASAR',
                'alamat' => 'Jl. Raya Sanur No. 15, Sanur, Denpasar, Bali',
                'pendidikan' => 'SEKOLAH MENENGAH ATAS',
                'pendidikan_terakhir' => 'SMA',
                'instansi_pendidikan' => 'SMA NEGERI 1 BANDUNG',
                'jurusan' => 'IPA',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2003,
                'handphone' => '+6281234567890',
                'no_telepon' => '+6281234567890',
                'email' => 'asep.setiawan@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-08-2041'),
                'grade' => 'VIII',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'LOST & FOUND OFFICER',
                'weight' => 68,
                'height' => 165,
                'organization_id' => 2,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 5
            [
                'no' => 5,
                'nip' => '2201048',
                'nik' => null,
                'nama_lengkap' => 'A.A GEDE AGUNG WIRAJAYA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'AS',
                'unit_organisasi' => 'Airside',
                'nama_organisasi' => 'LOAD CONTROL OPERATIONS',
                'nama_jabatan' => 'LOAD CONTROL',
                'jabatan' => 'LOAD CONTROL',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('10/03/2021'),
                'tmt_mulai_jabatan' => $this->parseDate('2021-03-10'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '42',
                'tempat_lahir' => 'DENPASAR',
                'tanggal_lahir' => $this->parseDate('1985-03-15'),
                'usia' => 40,
                'kota_domisili' => 'DENPASAR',
                'alamat' => 'Jl. Raya Denpasar No. 123, Denpasar, Bali',
                'pendidikan' => 'SARJANA',
                'pendidikan_terakhir' => 'S1',
                'instansi_pendidikan' => 'UNIVERSITAS UDAYANA',
                'jurusan' => 'TEKNIK MESIN',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2008,
                'handphone' => '+6281234567801',
                'no_telepon' => '+6281234567801',
                'email' => 'agung.wirajaya@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-03-2041'),
                'grade' => 'VIII',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'LOAD CONTROL OFFICER',
                'weight' => 72,
                'height' => 168,
                'organization_id' => 2,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 6
            [
                'no' => 6,
                'nip' => '2012117',
                'nik' => null,
                'nama_lengkap' => 'A.A NGURAH DHARMA PUTRA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'AS',
                'unit_organisasi' => 'Airside',
                'nama_organisasi' => 'RAMP OPERATIONS',
                'nama_jabatan' => 'RAMP DISPATCH',
                'jabatan' => 'RAMP DISPATCH',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('01/06/2022'),
                'tmt_mulai_jabatan' => $this->parseDate('2022-06-01'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '41',
                'tempat_lahir' => 'GIANYAR',
                'tanggal_lahir' => $this->parseDate('1987-06-20'),
                'usia' => 38,
                'kota_domisili' => 'GIANYAR',
                'alamat' => 'Jl. Sunset Road No. 456, Kuta, Badung, Bali',
                'pendidikan' => 'DIPLOMA III',
                'pendidikan_terakhir' => 'D3',
                'instansi_pendidikan' => 'POLITEKNIK NEGERI BALI',
                'jurusan' => 'TEKNIK PENERBANGAN',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2010,
                'handphone' => '+6281234567802',
                'no_telepon' => '+6281234567802',
                'email' => 'dharma.putra2@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-06-2043'),
                'grade' => 'VII',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'RAMP DISPATCH OFFICER',
                'weight' => 65,
                'height' => 170,
                'organization_id' => 2,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 7
            [
                'no' => 7,
                'nip' => '2012124',
                'nik' => null,
                'nama_lengkap' => 'A.A. AYU CANDRAWATI',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'AS',
                'unit_organisasi' => 'Airside',
                'nama_organisasi' => 'LOAD CONTROL OPERATIONS',
                'nama_jabatan' => 'LOAD CONTROL',
                'jabatan' => 'LOAD CONTROL',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('15/09/2021'),
                'tmt_mulai_jabatan' => $this->parseDate('2021-09-15'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'P',
                'jenis_sepatu' => 'Pantofel',
                'ukuran_sepatu' => '37',
                'tempat_lahir' => 'BADUNG',
                'tanggal_lahir' => $this->parseDate('1990-09-12'),
                'usia' => 34,
                'kota_domisili' => 'BADUNG',
                'alamat' => 'Jl. Bypass Ngurah Rai No. 789, Badung, Bali',
                'pendidikan' => 'SARJANA',
                'pendidikan_terakhir' => 'S1',
                'instansi_pendidikan' => 'UNIVERSITAS UDAYANA',
                'jurusan' => 'MANAJEMEN',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2013,
                'handphone' => '+6281234567803',
                'no_telepon' => '+6281234567803',
                'email' => 'ayu.candrawati@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-09-2046'),
                'grade' => 'VII',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'LOAD CONTROL OFFICER',
                'weight' => 58,
                'height' => 160,
                'organization_id' => 2,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 8
            [
                'no' => 8,
                'nip' => '2019023',
                'nik' => null,
                'nama_lengkap' => 'I KOMANG AGUS WIRAWAN',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'AV',
                'unit_organisasi' => 'Avsec',
                'nama_organisasi' => 'AVIATION SECURITY',
                'nama_jabatan' => 'SECURITY OFFICER',
                'jabatan' => 'SECURITY OFFICER',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('15/02/2019'),
                'tmt_mulai_jabatan' => $this->parseDate('2019-02-15'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '42',
                'tempat_lahir' => 'KLUNGKUNG',
                'tanggal_lahir' => $this->parseDate('1988-11-05'),
                'usia' => 36,
                'kota_domisili' => 'KLUNGKUNG',
                'alamat' => 'Jl. Gatot Subroto No. 654, Klungkung, Bali',
                'pendidikan' => 'SEKOLAH MENENGAH ATAS',
                'pendidikan_terakhir' => 'SMA',
                'instansi_pendidikan' => 'SMA NEGERI 1 KLUNGKUNG',
                'jurusan' => 'IPA',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2007,
                'handphone' => '+6281234567804',
                'no_telepon' => '+6281234567804',
                'email' => 'agus.wirawan@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-11-2044'),
                'grade' => 'VII',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'SECURITY OFFICER',
                'weight' => 70,
                'height' => 172,
                'organization_id' => 5,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 9
            [
                'no' => 9,
                'nip' => '2015089',
                'nik' => null,
                'nama_lengkap' => 'I MADE BAYU DINATA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'TAD',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'GSE',
                'unit_organisasi' => 'GSE',
                'nama_organisasi' => 'GROUND SUPPORT EQUIPMENT',
                'nama_jabatan' => 'OPERATOR GSE',
                'jabatan' => 'OPERATOR GSE',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('10/01/2023'),
                'tmt_mulai_jabatan' => $this->parseDate('2023-01-10'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '41',
                'tempat_lahir' => 'DENPASAR',
                'tanggal_lahir' => $this->parseDate('1985-01-18'),
                'usia' => 40,
                'kota_domisili' => 'DENPASAR',
                'alamat' => 'Jl. Teuku Umar No. 987, Denpasar, Bali',
                'pendidikan' => 'DIPLOMA III',
                'pendidikan_terakhir' => 'D3',
                'instansi_pendidikan' => 'POLITEKNIK NEGERI BALI',
                'jurusan' => 'TEKNIK MESIN',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2008,
                'handphone' => '+6281234567805',
                'no_telepon' => '+6281234567805',
                'email' => 'bayu.dinata@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-01-2041'),
                'grade' => 'VI',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'GSE OPERATOR',
                'weight' => 75,
                'height' => 168,
                'organization_id' => 3,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 10
            [
                'no' => 10,
                'nip' => '2012140',
                'nik' => null,
                'nama_lengkap' => 'I NYOMAN JOHN SUPARTA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'AS',
                'unit_organisasi' => 'Airside',
                'nama_organisasi' => 'RAMP OPERATIONS',
                'nama_jabatan' => 'RAMP DISPATCH',
                'jabatan' => 'RAMP DISPATCH',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('15/01/2022'),
                'tmt_mulai_jabatan' => $this->parseDate('2022-01-15'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '44',
                'tempat_lahir' => 'BULELENG',
                'tanggal_lahir' => $this->parseDate('1986-12-03'),
                'usia' => 38,
                'kota_domisili' => 'BULELENG',
                'alamat' => 'Jl. Diponegoro No. 147, Buleleng, Bali',
                'pendidikan' => 'SARJANA',
                'pendidikan_terakhir' => 'S1',
                'instansi_pendidikan' => 'UNIVERSITAS PENDIDIKAN GANESHA',
                'jurusan' => 'TEKNIK INFORMATIKA',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2009,
                'handphone' => '+6281234567806',
                'no_telepon' => '+6281234567806',
                'email' => 'john.suparta@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-12-2042'),
                'grade' => 'VII',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'RAMP DISPATCH OFFICER',
                'weight' => 80,
                'height' => 175,
                'organization_id' => 2,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 11
            [
                'no' => 11,
                'nip' => '2018045',
                'nik' => null,
                'nama_lengkap' => 'NI PUTU SARI DEWI',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'BO',
                'unit_organisasi' => 'Back Office',
                'nama_organisasi' => 'ADMINISTRATION',
                'nama_jabatan' => 'STAFF ADMINISTRASI',
                'jabatan' => 'STAFF ADMINISTRASI',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('15/04/2020'),
                'tmt_mulai_jabatan' => $this->parseDate('2020-04-15'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'P',
                'jenis_sepatu' => 'Pantofel',
                'ukuran_sepatu' => '36',
                'tempat_lahir' => 'BADUNG',
                'tanggal_lahir' => $this->parseDate('1992-04-22'),
                'usia' => 33,
                'kota_domisili' => 'BADUNG',
                'alamat' => 'Jl. Raya Kuta No. 258, Kuta, Badung, Bali',
                'pendidikan' => 'DIPLOMA III',
                'pendidikan_terakhir' => 'D3',
                'instansi_pendidikan' => 'STIKOM BALI',
                'jurusan' => 'SISTEM INFORMASI',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2015,
                'handphone' => '+6281234567807',
                'no_telepon' => '+6281234567807',
                'email' => 'sari.dewi@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-04-2048'),
                'grade' => 'VI',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'ADMIN STAFF',
                'weight' => 55,
                'height' => 158,
                'organization_id' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 12
            [
                'no' => 12,
                'nip' => '2020156',
                'nik' => null,
                'nama_lengkap' => 'KADEK RINA ASTUTI',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'LS',
                'unit_organisasi' => 'Landside',
                'nama_organisasi' => 'LANDSIDE OPERATIONS',
                'nama_jabatan' => 'LOAD CONTROL OFFICER',
                'jabatan' => 'LOAD CONTROL OFFICER',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('01/07/2021'),
                'tmt_mulai_jabatan' => $this->parseDate('2021-07-01'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'P',
                'jenis_sepatu' => 'Pantofel',
                'ukuran_sepatu' => '38',
                'tempat_lahir' => 'GIANYAR',
                'tanggal_lahir' => $this->parseDate('1993-07-14'),
                'usia' => 32,
                'kota_domisili' => 'GIANYAR',
                'alamat' => 'Jl. Hayam Wuruk No. 369, Gianyar, Bali',
                'pendidikan' => 'SARJANA',
                'pendidikan_terakhir' => 'S1',
                'instansi_pendidikan' => 'UNIVERSITAS UDAYANA',
                'jurusan' => 'EKONOMI',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2016,
                'handphone' => '+6281234567808',
                'no_telepon' => '+6281234567808',
                'email' => 'rina.astuti@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-07-2049'),
                'grade' => 'VI',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'LOAD CONTROL OFFICER',
                'weight' => 52,
                'height' => 162,
                'organization_id' => 4,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 13
            [
                'no' => 13,
                'nip' => '2019078',
                'nik' => null,
                'nama_lengkap' => 'WAYAN BAGUS SANTIKA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'AV',
                'unit_organisasi' => 'Avsec',
                'nama_organisasi' => 'AVIATION SECURITY',
                'nama_jabatan' => 'SECURITY SUPERVISOR',
                'jabatan' => 'SECURITY SUPERVISOR',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('15/10/2020'),
                'tmt_mulai_jabatan' => $this->parseDate('2020-10-15'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '42',
                'tempat_lahir' => 'DENPASAR',
                'tanggal_lahir' => $this->parseDate('1989-10-30'),
                'usia' => 35,
                'kota_domisili' => 'DENPASAR',
                'alamat' => 'Jl. Gajah Mada No. 741, Denpasar, Bali',
                'pendidikan' => 'SARJANA',
                'pendidikan_terakhir' => 'S1',
                'instansi_pendidikan' => 'UNIVERSITAS UDAYANA',
                'jurusan' => 'HUKUM',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2012,
                'handphone' => '+6281234567809',
                'no_telepon' => '+6281234567809',
                'email' => 'bagus.santika@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-10-2045'),
                'grade' => 'VII',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'SUPERVISOR',
                'kelas_jabatan' => 'SECURITY SUPERVISOR',
                'weight' => 78,
                'height' => 173,
                'organization_id' => 5,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 14
            [
                'no' => 14,
                'nip' => '2021189',
                'nik' => null,
                'nama_lengkap' => 'I GEDE WIRA KUSUMA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'GSE',
                'unit_organisasi' => 'GSE',
                'nama_organisasi' => 'GROUND SUPPORT EQUIPMENT',
                'nama_jabatan' => 'GSE TECHNICIAN',
                'jabatan' => 'GSE TECHNICIAN',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('01/08/2021'),
                'tmt_mulai_jabatan' => $this->parseDate('2021-08-01'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '43',
                'tempat_lahir' => 'KARANGASEM',
                'tanggal_lahir' => $this->parseDate('1990-11-25'),
                'usia' => 34,
                'kota_domisili' => 'KARANGASEM',
                'alamat' => 'Jl. Raya Candidasa No. 45, Karangasem, Bali',
                'pendidikan' => 'SEKOLAH MENENGAH KEJURUAN',
                'pendidikan_terakhir' => 'SMK',
                'instansi_pendidikan' => 'SMK NEGERI 1 KARANGASEM',
                'jurusan' => 'TEKNIK OTOMOTIF',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2009,
                'handphone' => '+6281234567810',
                'no_telepon' => '+6281234567810',
                'email' => 'wira.kusuma@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-11-2046'),
                'grade' => 'VI',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'GSE TECHNICIAN',
                'weight' => 82,
                'height' => 176,
                'organization_id' => 3,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 15
            [
                'no' => 15,
                'nip' => '2022234',
                'nik' => null,
                'nama_lengkap' => 'NI MADE INDIRA SARI',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'FN',
                'unit_organisasi' => 'Finance',
                'nama_organisasi' => 'FINANCE & ACCOUNTING',
                'nama_jabatan' => 'ACCOUNTING STAFF',
                'jabatan' => 'ACCOUNTING STAFF',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('01/03/2022'),
                'tmt_mulai_jabatan' => $this->parseDate('2022-03-01'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'P',
                'jenis_sepatu' => 'Pantofel',
                'ukuran_sepatu' => '39',
                'tempat_lahir' => 'TABANAN',
                'tanggal_lahir' => $this->parseDate('1995-02-14'),
                'usia' => 30,
                'kota_domisili' => 'TABANAN',
                'alamat' => 'Jl. Gunung Batur No. 123, Tabanan, Bali',
                'pendidikan' => 'SARJANA',
                'pendidikan_terakhir' => 'S1',
                'instansi_pendidikan' => 'UNIVERSITAS MAHASARASWATI',
                'jurusan' => 'AKUNTANSI',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2018,
                'handphone' => '+6281234567811',
                'no_telepon' => '+6281234567811',
                'email' => 'indira.sari@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-02-2051'),
                'grade' => 'V',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'ACCOUNTING STAFF',
                'weight' => 50,
                'height' => 155,
                'organization_id' => 6,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 16
            [
                'no' => 16,
                'nip' => '2023278',
                'nik' => null,
                'nama_lengkap' => 'PUTU AGUS MAHENDRA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'GSE',
                'unit_organisasi' => 'GSE',
                'nama_organisasi' => 'GROUND SUPPORT EQUIPMENT',
                'nama_jabatan' => 'GSE SUPERVISOR',
                'jabatan' => 'GSE SUPERVISOR',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('01/05/2023'),
                'tmt_mulai_jabatan' => $this->parseDate('2023-05-01'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '41',
                'tempat_lahir' => 'JEMBRANA',
                'tanggal_lahir' => $this->parseDate('1987-09-10'),
                'usia' => 38,
                'kota_domisili' => 'JEMBRANA',
                'alamat' => 'Jl. Raya Negara No. 67, Jembrana, Bali',
                'pendidikan' => 'DIPLOMA III',
                'pendidikan_terakhir' => 'D3',
                'instansi_pendidikan' => 'POLITEKNIK NEGERI BALI',
                'jurusan' => 'TEKNIK ELEKTRO',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2010,
                'handphone' => '+6281234567812',
                'no_telepon' => '+6281234567812',
                'email' => 'agus.mahendra@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-09-2043'),
                'grade' => 'VII',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'SUPERVISOR',
                'kelas_jabatan' => 'GSE SUPERVISOR',
                'weight' => 73,
                'height' => 169,
                'organization_id' => 3,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 17
            [
                'no' => 17,
                'nip' => '2024345',
                'nik' => null,
                'nama_lengkap' => 'KOMANG SARI DEWI',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'FN',
                'unit_organisasi' => 'Finance',
                'nama_organisasi' => 'FINANCE & ACCOUNTING',
                'nama_jabatan' => 'FINANCE OFFICER',
                'jabatan' => 'FINANCE OFFICER',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('15/02/2024'),
                'tmt_mulai_jabatan' => $this->parseDate('2024-02-15'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'P',
                'jenis_sepatu' => 'Pantofel',
                'ukuran_sepatu' => '37',
                'tempat_lahir' => 'BANGLI',
                'tanggal_lahir' => $this->parseDate('1994-12-08'),
                'usia' => 30,
                'kota_domisili' => 'BANGLI',
                'alamat' => 'Jl. Raya Kintamani No. 234, Bangli, Bali',
                'pendidikan' => 'SARJANA',
                'pendidikan_terakhir' => 'S1',
                'instansi_pendidikan' => 'UNIVERSITAS PENDIDIKAN GANESHA',
                'jurusan' => 'MANAJEMEN KEUANGAN',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2017,
                'handphone' => '+6281234567813',
                'no_telepon' => '+6281234567813',
                'email' => 'sari.dewi@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-12-2050'),
                'grade' => 'V',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'FINANCE OFFICER',
                'weight' => 53,
                'height' => 157,
                'organization_id' => 6,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 18
            [
                'no' => 18,
                'nip' => '2024412',
                'nik' => null,
                'nama_lengkap' => 'WAYAN DIKA PRATAMA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'GSE',
                'unit_organisasi' => 'GSE',
                'nama_organisasi' => 'GROUND SUPPORT EQUIPMENT',
                'nama_jabatan' => 'GSE MAINTENANCE',
                'jabatan' => 'GSE MAINTENANCE',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('01/04/2024'),
                'tmt_mulai_jabatan' => $this->parseDate('2024-04-01'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '40',
                'tempat_lahir' => 'DENPASAR',
                'tanggal_lahir' => $this->parseDate('1996-05-18'),
                'usia' => 29,
                'kota_domisili' => 'DENPASAR',
                'alamat' => 'Jl. Sesetan No. 89, Denpasar, Bali',
                'pendidikan' => 'SEKOLAH MENENGAH KEJURUAN',
                'pendidikan_terakhir' => 'SMK',
                'instansi_pendidikan' => 'SMK NEGERI 2 DENPASAR',
                'jurusan' => 'TEKNIK MESIN',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2015,
                'handphone' => '+6281234567814',
                'no_telepon' => '+6281234567814',
                'email' => 'dika.pratama@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-05-2052'),
                'grade' => 'V',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'GSE MAINTENANCE',
                'weight' => 67,
                'height' => 167,
                'organization_id' => 3,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 19
            [
                'no' => 19,
                'nip' => '2024523',
                'nik' => null,
                'nama_lengkap' => 'NI LUH KADEK SRI WAHYUNI',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'FN',
                'unit_organisasi' => 'Finance',
                'nama_organisasi' => 'FINANCE & ACCOUNTING',
                'nama_jabatan' => 'BUDGET ANALYST',
                'jabatan' => 'BUDGET ANALYST',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('01/06/2024'),
                'tmt_mulai_jabatan' => $this->parseDate('2024-06-01'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'P',
                'jenis_sepatu' => 'Pantofel',
                'ukuran_sepatu' => '38',
                'tempat_lahir' => 'SINGARAJA',
                'tanggal_lahir' => $this->parseDate('1993-03-27'),
                'usia' => 32,
                'kota_domisili' => 'BULELENG',
                'alamat' => 'Jl. Ahmad Yani No. 156, Singaraja, Buleleng, Bali',
                'pendidikan' => 'SARJANA',
                'pendidikan_terakhir' => 'S1',
                'instansi_pendidikan' => 'UNIVERSITAS PENDIDIKAN GANESHA',
                'jurusan' => 'EKONOMI',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2016,
                'handphone' => '+6281234567815',
                'no_telepon' => '+6281234567815',
                'email' => 'sri.wahyuni@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-03-2049'),
                'grade' => 'V',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'BUDGET ANALYST',
                'weight' => 56,
                'height' => 161,
                'organization_id' => 6,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Employee 20
            [
                'no' => 20,
                'nip' => '2024634',
                'nik' => null,
                'nama_lengkap' => 'I GEDE MADE ARYA SUAMBA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'GSE',
                'unit_organisasi' => 'GSE',
                'nama_organisasi' => 'GROUND SUPPORT EQUIPMENT',
                'nama_jabatan' => 'GSE COORDINATOR',
                'jabatan' => 'GSE COORDINATOR',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => $this->parseDate('15/07/2024'),
                'tmt_mulai_jabatan' => $this->parseDate('2024-07-15'),
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => null,
                'masa_kerja_tahun' => null,
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '42',
                'tempat_lahir' => 'DENPASAR',
                'tanggal_lahir' => $this->parseDate('1991-01-30'),
                'usia' => 34,
                'kota_domisili' => 'DENPASAR',
                'alamat' => 'Jl. Cargo Permai No. 78, Denpasar, Bali',
                'pendidikan' => 'SARJANA',
                'pendidikan_terakhir' => 'S1',
                'instansi_pendidikan' => 'UNIVERSITAS UDAYANA',
                'jurusan' => 'TEKNIK INDUSTRI',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2014,
                'handphone' => '+6281234567816',
                'no_telepon' => '+6281234567816',
                'email' => 'arya.suamba@gapura.com',
                'kategori_karyawan' => null,
                'tmt_pensiun' => $this->parseDate('01-01-2047'),
                'grade' => 'VI',
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'COORDINATOR',
                'kelas_jabatan' => 'GSE COORDINATOR',
                'weight' => 79,
                'height' => 174,
                'organization_id' => 3,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert employees data one by one with error handling
        $successCount = 0;
        foreach ($employees as $employee) {
            try {
                DB::table('employees')->insert($employee);
                $successCount++;
            } catch (\Exception $e) {
                $this->command->error("Failed to insert employee {$employee['nama_lengkap']}: " . $e->getMessage());
            }
        }

        $this->command->info("Successfully seeded {$successCount} employees.");
        $this->command->info('Total employees created: ' . count($employees));
        
        // Display shoe distribution statistics
        $pantofels = collect($employees)->where('jenis_sepatu', 'Pantofel')->count();
        $safetyShoes = collect($employees)->where('jenis_sepatu', 'Safety Shoes')->count();
        
        $this->command->info('');
        $this->command->info('SHOE DISTRIBUTION:');
        $this->command->info("   Pantofel: {$pantofels} employees");
        $this->command->info("   Safety Shoes: {$safetyShoes} employees");
        $this->command->info('');
    }

    private function seedOrganizations()
    {
        $this->command->info('Seeding organizations...');

        $organizations = [
            [
                'id' => 1,
                'name' => 'Back Office',
                'code' => 'BO',
                'description' => 'Divisi Back Office Operations - General Affair & Administration, Finance',
                'location' => 'Bandar Udara Ngurah Rai',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Airside',
                'code' => 'AS',
                'description' => 'Divisi Airside Operations - Operation Services, Flight Operations & Ramp Services',
                'location' => 'Bandar Udara Ngurah Rai',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'GSE',
                'code' => 'GSE',
                'description' => 'Ground Support Equipment Division - GSE Operation & Maintenance',
                'location' => 'Bandar Udara Ngurah Rai',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Landside',
                'code' => 'LS',
                'description' => 'Divisi Landside Operations - MPA, MPL & Unschedule Flight',
                'location' => 'Bandar Udara Ngurah Rai',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Avsec',
                'code' => 'AV',
                'description' => 'Aviation Security Division',
                'location' => 'Bandar Udara Ngurah Rai',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Finance',
                'code' => 'FN',
                'description' => 'Finance Division - Accounting & Financial Management',
                'location' => 'Bandar Udara Ngurah Rai',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        foreach ($organizations as $organization) {
            DB::table('organizations')->insert($organization);
        }

        $this->command->info('Organizations seeded successfully.');
    }

    /**
     * Function to parse date from CSV format (dd/mm/yyyy or yyyy-mm-dd)
     */
    private function parseDate($dateString)
    {
        if (empty($dateString) || $dateString === '-' || $dateString === null) {
            return null;
        }

        try {
            // If format is dd/mm/yyyy
            if (strpos($dateString, '/') !== false) {
                return Carbon::createFromFormat('d/m/Y', $dateString)->format('Y-m-d');
            }
            // If format is dd-mm-yyyy
            else if (strpos($dateString, '-') !== false && strlen($dateString) <= 10) {
                // Try dd-mm-yyyy format first
                if (preg_match('/^\d{2}-\d{2}-\d{4}$/', $dateString)) {
                    return Carbon::createFromFormat('d-m-Y', $dateString)->format('Y-m-d');
                }
                // Otherwise try yyyy-mm-dd format
                else {
                    return Carbon::parse($dateString)->format('Y-m-d');
                }
            }
        } catch (\Exception $e) {
            return null;
        }

        return null;
    }

    /**
     * Function to get organization ID by unit name
     */
    private function getOrganizationId($unitName)
    {
        $mapping = [
            'Back Office' => 1,
            'Airside' => 2,
            'GSE' => 3,
            'Landside' => 4,
            'Avsec' => 5,
            'Finance' => 6,
        ];

        return $mapping[$unitName] ?? 1;
    }
}