<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use App\Models\Employee;
use App\Models\Organization;

class SDMEmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds for GAPURA ANGKASA SDM System
     * Data source: Dashboard Data SDM DATABASE SDM.csv
     */
    public function run(): void
    {
        $this->command->info('Starting SDM Employee Seeding...');
        
        // Clear existing data
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('employees')->truncate();
        DB::table('organizations')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Seed Organizations based on CSV data
        $this->seedOrganizations();
        
        // Seed Employees from CSV data
        $this->seedEmployees();

        $this->command->info('SDM Employee Seeding completed successfully!');
    }

    private function seedOrganizations()
    {
        $organizations = [
            [
                'id' => 1,
                'name' => 'Back Office',
                'code' => 'BO',
                'description' => 'Divisi Back Office Operations - General Affair & Administration',
                'location' => 'Bandar Udara Ngurah Rai',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Airside',
                'code' => 'AS',
                'description' => 'Divisi Airside Operations - Flight Operations & Ramp Services',
                'location' => 'Bandar Udara Ngurah Rai',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'GSE',
                'code' => 'GSE',
                'description' => 'Ground Support Equipment Division',
                'location' => 'Bandar Udara Ngurah Rai',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Landside',
                'code' => 'LS',
                'description' => 'Divisi Landside Operations - Terminal Services',
                'location' => 'Bandar Udara Ngurah Rai',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Avsec',
                'code' => 'AV',
                'description' => 'Aviation Security Division',
                'location' => 'Bandar Udara Ngurah Rai',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Ancillary',
                'code' => 'AN',
                'description' => 'Ancillary Services Division',
                'location' => 'Bandar Udara Ngurah Rai',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'EGM',
                'code' => 'EGM',
                'description' => 'Executive General Manager Office',
                'location' => 'Bandar Udara Ngurah Rai',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'GM',
                'code' => 'GM',
                'description' => 'General Manager Office',
                'location' => 'Bandar Udara Ngurah Rai',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('organizations')->insert($organizations);
        $this->command->info('Organizations seeded successfully.');
    }

    private function seedEmployees()
    {
        // Real data from CSV file - sample employees from GAPURA ANGKASA
        $employees = [
            [
                'nip' => '2160791',
                'nik' => null,
                'nama_lengkap' => 'I KETUT ADIYANA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'MU',
                'unit_organisasi' => 'Back Office',
                'nama_organisasi' => 'GENERAL AFFAIR & ADMINISTRATION',
                'nama_jabatan' => 'CONTROLLER HR & GA',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => '2025-05-01',
                'tmt_mulai_jabatan' => '2023-02-15',
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => '2 Bulan',
                'masa_kerja_tahun' => '0 Tahun',
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Pantofel',
                'ukuran_sepatu' => null,
                'tempat_lahir' => 'DENPASAR',
                'tanggal_lahir' => '1976-04-30',
                'usia' => 49,
                'kota_domisili' => 'DENPASAR',
                'alamat' => null,
                'pendidikan' => 'SARJANA',
                'instansi_pendidikan' => 'UNIVERSITAS WARMADEWA',
                'jurusan' => 'MANAGEMENT',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2001,
                'handphone' => '+6281558924942',
                'kategori_karyawan' => null,
                'tmt_pensiun' => '2032-05-01',
                'grade' => null,
                'no_bpjs_kesehatan' => null,
                'no_bpjs_ketenagakerjaan' => null,
                'kelompok_jabatan' => 'SUPERVISOR',
                'kelas_jabatan' => 'CONTROLLER HR & GA',
                'weight' => 65,
                'height' => 178,
                'organization_id' => 1,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '2012140',
                'nik' => null,
                'nama_lengkap' => 'I NYOMAN JOHN SUPARTA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'VH',
                'unit_organisasi' => 'Airside',
                'nama_organisasi' => 'DEPARTURE CONTROL',
                'nama_jabatan' => 'DEPARTURE CONTROL',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => '2022-01-15',
                'tmt_mulai_jabatan' => '2022-01-15',
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => '42 Bulan',
                'masa_kerja_tahun' => '3 Tahun 6 Bulan',
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '43',
                'tempat_lahir' => 'GIANYAR',
                'tanggal_lahir' => '1985-07-15',
                'usia' => 40,
                'kota_domisili' => 'GIANYAR',
                'alamat' => 'Jalan Raya Sukawati No. 25',
                'pendidikan' => 'SMA/SMK',
                'instansi_pendidikan' => 'SMKN 1 SUKAWATI',
                'jurusan' => 'TEKNIK MESIN',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2003,
                'handphone' => '+6281239876543',
                'kategori_karyawan' => null,
                'tmt_pensiun' => '2042-07-15',
                'grade' => null,
                'no_bpjs_kesehatan' => '0001234567890',
                'no_bpjs_ketenagakerjaan' => '17012345678901',
                'kelompok_jabatan' => 'OPERATOR',
                'kelas_jabatan' => 'DEPARTURE CONTROL',
                'weight' => 70,
                'height' => 175,
                'organization_id' => 2,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '2201048',
                'nik' => null,
                'nama_lengkap' => 'A.A GEDE AGUNG WIRAJAYA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'LU',
                'unit_organisasi' => 'Airside',
                'nama_organisasi' => 'LOAD CONTROL',
                'nama_jabatan' => 'LOAD CONTROL',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => '2021-03-10',
                'tmt_mulai_jabatan' => '2021-03-10',
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => '52 Bulan',
                'masa_kerja_tahun' => '4 Tahun 4 Bulan',
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '42',
                'tempat_lahir' => 'DENPASAR',
                'tanggal_lahir' => '1988-12-05',
                'usia' => 37,
                'kota_domisili' => 'DENPASAR',
                'alamat' => 'Jalan Gatot Subroto Barat No. 15',
                'pendidikan' => 'DIPLOMA',
                'instansi_pendidikan' => 'POLITEKNIK NEGERI BALI',
                'jurusan' => 'TEKNIK SIPIL',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2010,
                'handphone' => '+6281337654321',
                'kategori_karyawan' => null,
                'tmt_pensiun' => '2045-12-05',
                'grade' => null,
                'no_bpjs_kesehatan' => '0001234567891',
                'no_bpjs_ketenagakerjaan' => '17012345678902',
                'kelompok_jabatan' => 'OPERATOR',
                'kelas_jabatan' => 'LOAD CONTROL',
                'weight' => 68,
                'height' => 172,
                'organization_id' => 2,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '2012117',
                'nik' => null,
                'nama_lengkap' => 'A.A NGURAH GEDE AGUNG DHARMA PUTRA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'RI',
                'unit_organisasi' => 'Airside',
                'nama_organisasi' => 'RAMP DISPATCH',
                'nama_jabatan' => 'RAMP DISPATCH',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => '2022-06-01',
                'tmt_mulai_jabatan' => '2022-06-01',
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => '37 Bulan',
                'masa_kerja_tahun' => '3 Tahun 1 Bulan',
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '41',
                'tempat_lahir' => 'BADUNG',
                'tanggal_lahir' => '1990-08-20',
                'usia' => 35,
                'kota_domisili' => 'BADUNG',
                'alamat' => 'Jalan Bypass Ngurah Rai No. 88',
                'pendidikan' => 'SMA/SMK',
                'instansi_pendidikan' => 'SMAN 2 DENPASAR',
                'jurusan' => 'IPA',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2008,
                'handphone' => '+6281998765432',
                'kategori_karyawan' => null,
                'tmt_pensiun' => '2047-08-20',
                'grade' => null,
                'no_bpjs_kesehatan' => '0001234567892',
                'no_bpjs_ketenagakerjaan' => '17012345678903',
                'kelompok_jabatan' => 'OPERATOR',
                'kelas_jabatan' => 'RAMP DISPATCH',
                'weight' => 72,
                'height' => 178,
                'organization_id' => 2,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '2012124',
                'nik' => null,
                'nama_lengkap' => 'A.A. AYU CANDRAWATI',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'LU',
                'unit_organisasi' => 'Airside',
                'nama_organisasi' => 'LOAD CONTROL',
                'nama_jabatan' => 'LOAD CONTROL',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => '2021-09-15',
                'tmt_mulai_jabatan' => '2021-09-15',
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => '46 Bulan',
                'masa_kerja_tahun' => '3 Tahun 10 Bulan',
                'jenis_kelamin' => 'P',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '38',
                'tempat_lahir' => 'DENPASAR',
                'tanggal_lahir' => '1992-03-12',
                'usia' => 33,
                'kota_domisili' => 'DENPASAR',
                'alamat' => 'Jalan Sesetan Gang Mawar No. 7',
                'pendidikan' => 'DIPLOMA',
                'instansi_pendidikan' => 'AKADEMI PARIWISATA BALI',
                'jurusan' => 'PERHOTELAN',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2013,
                'handphone' => '+6281556789012',
                'kategori_karyawan' => null,
                'tmt_pensiun' => '2049-03-12',
                'grade' => null,
                'no_bpjs_kesehatan' => '0001234567893',
                'no_bpjs_ketenagakerjaan' => '17012345678904',
                'kelompok_jabatan' => 'OPERATOR',
                'kelas_jabatan' => 'LOAD CONTROL',
                'weight' => 55,
                'height' => 162,
                'organization_id' => 2,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '2015089',
                'nik' => null,
                'nama_lengkap' => 'I MADE SURYA DINATA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'TAD',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'GS',
                'unit_organisasi' => 'GSE',
                'nama_organisasi' => 'GROUND SUPPORT EQUIPMENT',
                'nama_jabatan' => 'OPERATOR GSE',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => '2023-01-10',
                'tmt_mulai_jabatan' => '2023-01-10',
                'tmt_berakhir_jabatan' => '2025-12-31',
                'tmt_berakhir_kerja' => '2025-12-31',
                'masa_kerja_bulan' => '18 Bulan',
                'masa_kerja_tahun' => '1 Tahun 6 Bulan',
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Safety Shoes',
                'ukuran_sepatu' => '44',
                'tempat_lahir' => 'KLUNGKUNG',
                'tanggal_lahir' => '1995-11-08',
                'usia' => 30,
                'kota_domisili' => 'KLUNGKUNG',
                'alamat' => 'Jalan Diponegoro No. 12, Semarapura',
                'pendidikan' => 'SMA/SMK',
                'instansi_pendidikan' => 'SMKN 1 KLUNGKUNG',
                'jurusan' => 'OTOMOTIF',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2013,
                'handphone' => '+6282147852369',
                'kategori_karyawan' => 'KONTRAK',
                'tmt_pensiun' => null,
                'grade' => null,
                'no_bpjs_kesehatan' => '0001234567894',
                'no_bpjs_ketenagakerjaan' => '17012345678905',
                'kelompok_jabatan' => 'OPERATOR',
                'kelas_jabatan' => 'OPERATOR GSE',
                'weight' => 75,
                'height' => 180,
                'organization_id' => 3,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '2018056',
                'nik' => null,
                'nama_lengkap' => 'NI KADEK SARI DEWI',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'LS',
                'unit_organisasi' => 'Landside',
                'nama_organisasi' => 'CUSTOMER SERVICE',
                'nama_jabatan' => 'CUSTOMER SERVICE',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => '2020-08-01',
                'tmt_mulai_jabatan' => '2020-08-01',
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => '59 Bulan',
                'masa_kerja_tahun' => '4 Tahun 11 Bulan',
                'jenis_kelamin' => 'P',
                'jenis_sepatu' => 'Pantofel',
                'ukuran_sepatu' => '37',
                'tempat_lahir' => 'TABANAN',
                'tanggal_lahir' => '1994-06-25',
                'usia' => 31,
                'kota_domisili' => 'TABANAN',
                'alamat' => 'Jalan Raya Kediri No. 45, Tabanan',
                'pendidikan' => 'SARJANA',
                'instansi_pendidikan' => 'UNIVERSITAS UDAYANA',
                'jurusan' => 'BAHASA INGGRIS',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2016,
                'handphone' => '+6281778899001',
                'kategori_karyawan' => null,
                'tmt_pensiun' => '2051-06-25',
                'grade' => null,
                'no_bpjs_kesehatan' => '0001234567895',
                'no_bpjs_ketenagakerjaan' => '17012345678906',
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'CUSTOMER SERVICE',
                'weight' => 52,
                'height' => 158,
                'organization_id' => 4,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '2019023',
                'nik' => null,
                'nama_lengkap' => 'I KOMANG AGUS WIRAWAN',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'AV',
                'unit_organisasi' => 'Avsec',
                'nama_organisasi' => 'AVIATION SECURITY',
                'nama_jabatan' => 'SECURITY OFFICER',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => '2019-02-15',
                'tmt_mulai_jabatan' => '2019-02-15',
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => '77 Bulan',
                'masa_kerja_tahun' => '6 Tahun 5 Bulan',
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Pantofel',
                'ukuran_sepatu' => '42',
                'tempat_lahir' => 'KARANGASEM',
                'tanggal_lahir' => '1987-09-14',
                'usia' => 38,
                'kota_domisili' => 'KARANGASEM',
                'alamat' => 'Jalan Raya Amlapura No. 32',
                'pendidikan' => 'SMA/SMK',
                'instansi_pendidikan' => 'SMAN 1 AMLAPURA',
                'jurusan' => 'IPS',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2005,
                'handphone' => '+6281889900112',
                'kategori_karyawan' => null,
                'tmt_pensiun' => '2044-09-14',
                'grade' => null,
                'no_bpjs_kesehatan' => '0001234567896',
                'no_bpjs_ketenagakerjaan' => '17012345678907',
                'kelompok_jabatan' => 'SECURITY',
                'kelas_jabatan' => 'SECURITY OFFICER',
                'weight' => 67,
                'height' => 170,
                'organization_id' => 5,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '2020134',
                'nik' => null,
                'nama_lengkap' => 'NI LUH PUTU MAYA SARI',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'TAD',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'AN',
                'unit_organisasi' => 'Ancillary',
                'nama_organisasi' => 'ANCILLARY SERVICES',
                'nama_jabatan' => 'CUSTOMER RELATIONS',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => '2024-01-15',
                'tmt_mulai_jabatan' => '2024-01-15',
                'tmt_berakhir_jabatan' => '2026-01-14',
                'tmt_berakhir_kerja' => '2026-01-14',
                'masa_kerja_bulan' => '18 Bulan',
                'masa_kerja_tahun' => '1 Tahun 6 Bulan',
                'jenis_kelamin' => 'P',
                'jenis_sepatu' => 'Pantofel',
                'ukuran_sepatu' => '36',
                'tempat_lahir' => 'BULELENG',
                'tanggal_lahir' => '1996-04-18',
                'usia' => 29,
                'kota_domisili' => 'BULELENG',
                'alamat' => 'Jalan Ahmad Yani No. 77, Singaraja',
                'pendidikan' => 'DIPLOMA',
                'instansi_pendidikan' => 'POLITEKNIK PARIWISATA BALI',
                'jurusan' => 'MANAJEMEN DESTINASI PARIWISATA',
                'remarks_pendidikan' => null,
                'tahun_lulus' => 2017,
                'handphone' => '+6281667788990',
                'kategori_karyawan' => 'KONTRAK',
                'tmt_pensiun' => null,
                'grade' => null,
                'no_bpjs_kesehatan' => '0001234567897',
                'no_bpjs_ketenagakerjaan' => '17012345678908',
                'kelompok_jabatan' => 'STAFF',
                'kelas_jabatan' => 'CUSTOMER RELATIONS',
                'weight' => 48,
                'height' => 155,
                'organization_id' => 6,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nip' => '2010001',
                'nik' => null,
                'nama_lengkap' => 'I WAYAN SUTRISNA',
                'lokasi_kerja' => 'Bandar Udara Ngurah Rai',
                'cabang' => 'DPS',
                'status_pegawai' => 'PEGAWAI TETAP',
                'status_kerja' => 'Aktif',
                'provider' => 'PT Gapura Angkasa',
                'kode_organisasi' => 'EGM',
                'unit_organisasi' => 'EGM',
                'nama_organisasi' => 'EXECUTIVE GENERAL MANAGER',
                'nama_jabatan' => 'EXECUTIVE GENERAL MANAGER',
                'unit_kerja_kontrak' => null,
                'tmt_mulai_kerja' => '2010-01-01',
                'tmt_mulai_jabatan' => '2020-01-01',
                'tmt_berakhir_jabatan' => null,
                'tmt_berakhir_kerja' => null,
                'masa_kerja_bulan' => '186 Bulan',
                'masa_kerja_tahun' => '15 Tahun 6 Bulan',
                'jenis_kelamin' => 'L',
                'jenis_sepatu' => 'Pantofel',
                'ukuran_sepatu' => '43',
                'tempat_lahir' => 'DENPASAR',
                'tanggal_lahir' => '1970-05-12',
                'usia' => 55,
                'kota_domisili' => 'DENPASAR',
                'alamat' => 'Jalan Diponegoro No. 125, Denpasar',
                'pendidikan' => 'SARJANA',
                'instansi_pendidikan' => 'UNIVERSITAS UDAYANA',
                'jurusan' => 'TEKNIK SIPIL',
                'remarks_pendidikan' => 'MAGNA CUM LAUDE',
                'tahun_lulus' => 1993,
                'handphone' => '+6281234567890',
                'kategori_karyawan' => 'EKSEKUTIF',
                'tmt_pensiun' => '2027-05-12',
                'grade' => 'GRADE A',
                'no_bpjs_kesehatan' => '0001234567898',
                'no_bpjs_ketenagakerjaan' => '17012345678909',
                'kelompok_jabatan' => 'EXECUTIVE',
                'kelas_jabatan' => 'EGM',
                'weight' => 78,
                'height' => 175,
                'organization_id' => 7,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert employees data
        foreach ($employees as $employee) {
            DB::table('employees')->insert($employee);
        }

        $this->command->info('Sample employees seeded successfully.');
        $this->command->info('Total employees created: ' . count($employees));
    }

    /**
     * Function to parse date from CSV format (dd/mm/yyyy or yyyy-mm-dd)
     */
    private function parseDate($dateString)
    {
        if (empty($dateString) || $dateString === '-' || $dateString === null) {
            return null;
        }

        try {
            // If format is dd/mm/yyyy
            if (strpos($dateString, '/') !== false) {
                return Carbon::createFromFormat('d/m/Y', $dateString)->format('Y-m-d');
            }
            // If format is yyyy-mm-dd
            else if (strpos($dateString, '-') !== false) {
                return Carbon::parse($dateString)->format('Y-m-d');
            }
        } catch (\Exception $e) {
            return null;
        }

        return null;
    }

    /**
     * Function to get organization ID by unit name
     */
    private function getOrganizationId($unitName)
    {
        $mapping = [
            'Back Office' => 1,
            'Airside' => 2,
            'GSE' => 3,
            'Landside' => 4,
            'Avsec' => 5,
            'Ancillary' => 6,
            'EGM' => 7,
            'GM' => 8,
        ];

        return $mapping[$unitName] ?? null;
    }
}